### PR TITLE
Food Recipe project

### PR DESCRIPTION
**Pull request by Tommymarvel**
### In this project, we have implemented different functionalities, which include :

- Using javascript to render objects dynamically
- We've also added counters to our like button and comment section.
- We've used Jest to test the functions and it's working perfectly.
- API is also used in this project for involvement and visuals.
- Check this [LIVE](https://kusilaw.github.io/food_recipies/dist/).
- [Watch](https://www.loom.com/share/c53751aaf7c347aeb47fee3a2c11e12f ) the presentation.

#### Note: This is a group of two students.

### CODE REVIEW

**Review by VICTOR-CHUKWU — CHANGES_REQUESTED** [review]
Hi Team, 
## STATUS: CHANGES REQUIRED :recycle: 
Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._
- [ ] They should be a counter at the top of your page below your nav bar showing the number of items in your page
Screenshot from 2022-09-09 17-19-35
kindly add this and your project will be complete

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Tommymarvel** [comment]
> Hi Team,
> 
> ## STATUS: CHANGES REQUIRED 
> Good job so far! There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
> 
> ## Suggested changes
> _Check the comments under the review._
> 
> * [ ]  They should be a counter at the top of your page below your nav bar showing the number of items in your page
>   Screenshot from 2022-09-09 17-19-35
>   kindly add this and your project will be complete
> 
> You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Tommymarvel** [comment]
> Hi Team,
> 
> ## STATUS: CHANGES REQUIRED 
> Good job so far! There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
> 
> ## Suggested changes
> _Check the comments under the review._
> 
> * [ ]  They should be a counter at the top of your page below your nav bar showing the number of items in your page
>   Screenshot from 2022-09-09 17-19-35
>   kindly add this and your project will be complete
> 
> You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

@VICTOR-CHUKWU  Thank you for your time to review the project, we really appreciate it, the counter is there but maybe because of the color, we suggest you re-check

**Comment by VICTOR-CHUKWU** [comment]
I just saw it now, kindly resubmit for the next reviewer to approve, and you can make it look more visible, thanks :clap:

**Review by aimemalaika — APPROVED** [review]
Hi <STUDENT_MENTION>, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
